name: Clojure CI

on: 
  push:
    branches: 
      - production

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: cache_node_js
      uses:  actions/cache@v1
      env:
        cache-name: node-modules
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install react

    
    - name: Cache_leiningen_depth
      uses: actions/cache@v1
      env:
        cache-name: cache-lein-deps
      with: 
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    
    - name: Install dependencies
      run: lein deps

    - name: build cljs	
      run: lein prod	

    - name: build garden	
      run: lein garden once	
      
    - name: Commit files
      run: |
        git config --local user.email "meguru.mokke@gmail.com"
        git config --local user.name "MokkeMeguru"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Build from production"
        git push
