name: Clojure CI

on: 
  push:
    branches: 
      - deploy

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache_leiningen_depth
      uses: actions/cache@v1
      env:
        cache-name: cache-lein-deps
      with: 
        path: ~/.lein
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: lein deps

    - name: build cljs
      run: lein prod

    - name: build garden
      run: lein garden once

    - name: deploy-action
      uses: rohit-gohri/deploy-action@v0.1.0
      env:
        DEPLOY_ENV: production
        DEPLOY_REF: master
        GITHUB_TOKEN:  ${{ secrets.gh-pages }}
