name: firebase-deploy

on:
  push:
    branches:
      - firebase-deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project portfolio-megurumokke
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
