name: firebase-deploy

on:
  push:
    branches:
      - firebase

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: cache_node_js
      uses:  actions/cache@v1
      env:
        cache-name: node-modules
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install react

    
    - name: Cache_leiningen_depth
      uses: actions/cache@v1
      env:
        cache-name: cache-lein-deps
      with: 
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Install dependencies
      run: lein deps

    - name: build cljs	
      run: lein prod	

    - name: build garden	
      run: lein garden once	

  deploy:

    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting --project portfolio-megurumokke
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: resources/public
